name = "dogenode-backend"
main = "src/index.js"
compatibility_date = "2024-12-05"

# SECCIÓN AVANZADA: Ignora los módulos internos de Node.js para el bundler
[build]
# Esto le dice a esbuild que no procese módulos nativos, sino que los deje como están
# para que la bandera nodejs_compat los maneje en tiempo de ejecución.
external = ["fs", "path", "stream", "crypto", "net", "async_hooks", "buffer", "zlib", "util", "querystring"]
